// export const AUTH__LOGIN = 'AUTH__LOGIN';
// export const AUTH__LOGOUT = 'AUTH__LOGOUT';
// export const AUTH__CHECK = 'AUTH__CHECK';
// export const AUTH__HIDE_ERROR = 'AUTH__HIDE_ERROR';
// export const AUTH__SET_LOGGED = 'AUTH__SET_LOGGED';
// export const AUTH__SET_UNLOGGED = 'AUTH__SET_UNLOGGED';
// export const AUTH__LOGIN_FAILED = 'AUTH__LOGIN_FAILED';
// export const AUTH__SET_LOADING = 'AUTH__SET_LOADING';
// export const AUTH__HIDE_LOADING = 'AUTH__HIDE_LOADING';
//
export enum EAuthActionTypes {
    AUTH__LOGIN = 'AUTH__LOGIN',
    AUTH__LOGOUT = 'AUTH__LOGOUT',
    AUTH__CHECK = 'AUTH__CHECK',
    AUTH__HIDE_ERROR = 'AUTH__HIDE_ERROR',
    AUTH__SET_LOGGED = 'AUTH__SET_LOGGED',
    AUTH__SET_UNLOGGED = 'AUTH__SET_UNLOGGED',
    AUTH__LOGIN_FAILED = 'AUTH__LOGIN_FAILED',
    AUTH__SET_LOADING = 'AUTH__SET_LOADING',
    AUTH__HIDE_LOADING = 'AUTH__HIDE_LOADING',
    AUTH__SET_AUTH_USER = 'AUTH__SET_AUTH_USER',
}
export enum ECommonActionTypes {
    COMMON__SHOW_LOADING = 'COMMON__SHOW_LOADING',
    COMMON__HIDE_LOADING = 'COMMON__HIDE_LOADING',
    COMMON__ACTIVE_TAB_CHANGING = 'COMMON__ACTIVE_TAB_CHANGING'
}